name: Sync to Vercel Repo

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This line stops GitHub from overriding your SYNC_PAT
          persist-credentials: false 

      - name: Force Push to Destination
        run: |
          git remote add destination https://x-access-token:${{ secrets.SYNC_PAT }}@github.com/villainletgalledev/villa-inlet-pms.git
          git push destination main --force
